responses = {
    r'\bname\b': "My name is Colby, and my creator's name is also Colby, although technically I think it's the other way around.",
    r'\bhobbies\b': "I have many hobbies! Some of which are: working out, gaming, watching anime and motorcycles.",
    r'\beducation\b': "I studied at Whickham Comprehensive School, then sixth form at Whickham and finally, attended Teesside University where I graduated with Honours.",
    r'\bskills\b': "I have many skills! Would you like to hear about my soft skills or technical skills?",
    r'\bsoft\b': "I'm very adaptable and a quick learner. I began my journey as a graduate and quickly became a skilled infrastructure engineer after only a year, skipping junior and being promoted straight to an associate level. I'm a great team worker and collaborator, excellent communicator, and of course, problem solver.",
    r'\btechnical\b': "I'm proficient with many AWS features, identity and access management, IAC, CI/CD solutions, cloud networking, scripting & automation, cost optimization, serverless infrastructure, and Python programming.",
    r'\blearning\b': "Currently, I'm studying for the AWS Solutions Architect exam, as well as learning more about serverless infrastructure, building my Python skills, containerization (Docker and Kubernetes), and Linux.",
    r'\bweaknesses\b': "I have trouble delegating work sometimes, and will often take on too much to handle. This is something I've improved upon though. I also have some weaknesses in my technical skills such as containerization, Linux, and general physical infrastructure, as I learned purely cloud past secondary school. A big weakness sometimes is my ability to converse, but this is due to a mental disability. However, I have greatly improved this over the years.",
    r'\bsalary\b': "My current salary (including bonus and extra benefits) is roughly £47,800. I'd be looking for a minimum of a 10% increase in that with a new role.",
    r'\bproject\b': "Currently, Me! I'm working on improving the chatbot's AI to be more adaptive, also looking at building a CI/CD Pipeline for my static website. In the future, possibly improve my Python skills and look into algorithms, as that interests me a lot.",
    r'\bexperience\b': "I currently have over two years of hands-on experience working with AWS at a large company, developing tools, infrastructure solutions, and handling BAU work daily.",
    r'\bhelp\b': "name, hobbies, education, skills, soft, technical, learning, weaknesses, salary, project, experience, achievements, certifications, future goals, languages, books, movies, travel, pet peeves, food, fitness, projects, quotes",
    r'\bachievements\b': "I've achieved several milestones in my career, including getting promoted to an associate level within a year.",
    r'\bcertifications\b': "I currently am revisinng for my AWS Certified Solutions Architect exam.",
    r'\bfuture goals\b|\bgoals\b': "In the future, I aim to enhance my skills as a programmer and a solutions architect. Deepen my knowledge of cloud computing, and move into a devops role. Ultimately achieving a leadership role where I can mentor and guide others.",
    r'\blanguages\b': "I'm proficient in English. I also have advanced knowledge in Python, terraform and HTML/CSS.",
    r'\bfavorite games\b|\games\b': "Some of my favorite games include: World of Warcraft, League of legends, The Wolf Among Us, Xcom 2, Dark souls and The tomb raider remaster series. ",
    r'\bfavorite movies\b|\bmovies\b': "I enjoy watching a variety of movies. Some of my favorites are Saving private ryan, Pulp Fiction, Scream, star wars and In Time.",
    r'\bpet peeves\b|\bannoy\b': "One of my pet peeves is poor communication/assumption in a team setting. Clear and concise communication is key to successful collaboration. Expecting the other person to know what to do froma  vague suggestion is not fun for anyone and builds a unclear picture for people.",
    r'\bfavorite foods\b|\bfood\b': "I love trying different cuisines, but I am BIG fan of sushi, far eastern rice and noodle dishes and well made steak.",
    r'\bquotes\b|\binspiration\b|\bmotto\b': "One of my favorite things to say is not a famous quote or anything, it's just 'it is what it is'. I try not to worry too hard or stress about things that aren't in my control, although I still do, as we're only human but this motto helps remind me not too!",
    r'.*': "Sorry, I don't understand that question. Could you try rephrasing it please?"
}
